### ISSUE TITLE
Hide arrows from scoped arguments

### ISSUE THREAD

**Issue by JGcarv** [ConsenSys/vscode-solidity-auditor#100]
Hi! First of all, I love this extensions and I've been using for a few good years now, so thank you for the hard work!

I just have one request, is there a way to keep the decoration from scoped arguments, like the background, but not display the extra arrow character? The arrow messes up a bit the formatting.

Thank you!

**Comment by tintinweb** [comment]
made this configurable (see #104). will be part of the next release. cheers 🙌
