### ISSUE TITLE
[Graph] Different styling for Custom Errors

### ISSUE THREAD

**Issue by C-Mierez** [ConsenSys/vscode-solidity-auditor#101]
Greetings.

This is a bit of niche suggestion perhaps, but I noticed when generating a graph on a contract that has [Custom Errors](https://blog.soliditylang.org/2021/04/21/custom-errors/) defined, these are graphed the same way as regular functions. 

For example, given this contract:
<img  height="400px" src="https://user-images.githubusercontent.com/54458726/163852406-12718241-e40c-43dd-8ae7-43e92abd8197.png" />

The generated graph is:
<img  height="400px" src="https://user-images.githubusercontent.com/54458726/163852636-c865df26-edfe-45af-aa79-b180b45f0419.png" />

I like the idea of having errors showing in the graph, but it would be nice if they had some different styling to tell them apart from actual contract functions.

> And as a side-note, it's interesting that events are not included at all. Perhaps that's something that could be looked into as well.

**Comment by tintinweb** [comment]
@GNSPS can you look into this? you're the king of graphing 🤗 Errors should probably be exempt from the graphing at all, wdyt?

**Comment by tintinweb** [comment]
opened a discussion with https://github.com/ConsenSys/surya/issues/170. please follow up there.

thanks for reporting & cheers 🙌
