### ISSUE TITLE
command 'solidity-va.surya.graph' not found on VSCode

### ISSUE THREAD

**Issue by elxandre** [ConsenSys/vscode-solidity-auditor#103]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/72232250/165504561-6520869d-0767-4d6e-99bb-dafd5b90d14f.png">

When using the VSCode extension, I encounter the command not found error. Could someone kindly advise?

**Comment by tintinweb** [comment]
can you try to help me reproduce this by sharing the exact steps that lead to this message?

**Comment by tintinweb** [comment]
cannot reproduce.

**Comment by wundergeu** [comment]
Got the same error. Basically none of the commands from the Command Palette is working. 'Command xxx not found'.
I got a pretty fresh installation of VS Code with only the solidity extension by Juan Blanco and this extension.

In the developer console it says: Activating extension 'tintinweb.solidity-visual-auditor' failed: Cannot read properties of undefined (reading 'map').
$onExtensionActivationError @ mainThreadExtensionService.ts:111
![sva](https://user-images.githubusercontent.com/118638389/202874333-18e2cded-acd8-4b74-9a68-e4901c9c1c9b.png)
