### ISSUE TITLE
`go to references` not working

### ISSUE THREAD

**Issue by faea726** [ConsenSys/vscode-solidity-auditor#119]
It cannot go to references anymore.
It also prevents other extensions from doing that.

I'm using `NomicFoundation.hardhat-solidity`, it has `go to references` option, quite nice.
But whenever I enable `tintinweb.solidity-visual-auditor`, the `go to references` is not working anymore.
When I disable `NomicFoundation.hardhat-solidity` and only use `tintinweb.solidity-visual-auditor`, the `go to references` still not working.

=> I think it's caused by `tintinweb.solidity-visual-auditor`. Please have a check on that.

![image](https://user-images.githubusercontent.com/37011495/200617129-eec9001e-024e-41ce-bf2e-a519a2f046d5.png)

**Comment by tonisives** [comment]
I tried to use previous versions (0.1.3 and 0.1.2) and the references still didn't work. I also tried to use previous juanblanco.solidity, but still didn't help

**Comment by faea726** [comment]
> I tried to use previous versions (0.1.3 and 0.1.2) and the references still didn't work. I also tried to use previous juanblanco.solidity, but still didn't help
> 
> edit: as a fix, you could disable auditor references with `"solidity-va.findAllReferences.enable": false`. Then vscode will use hardhat solidity references.

Work perfectly! Thanks for your suggestion.

**Comment by jmhickman** [comment]
I'm also experiencing this.

It coincided with my updating VSCode to 1.73.1. I rolled back my install to 1.72.x and it resumed working properly.

**Comment by mlafon** [comment]
```
[error] TypeError: Class constructor d cannot be invoked without 'new'
    at .vscode/extensions/tintinweb.solidity-visual-auditor-0.1.4/src/features/references.js:63:19
    at Array.forEach (<anonymous>)
    at indicesToVscodeRange (.vscode/extensions/tintinweb.solidity-visual-auditor-0.1.4/src/features/references.js:42:13)
    at .vscode/extensions/tintinweb.solidity-visual-auditor-0.1.4/src/features/references.js:92:25
    at async Promise.all (index 1)
    at async .vscode/extensions/tintinweb.solidity-visual-auditor-0.1.4/src/features/references.js:86:21
    at async .vscode/extensions/tintinweb.solidity-visual-auditor-0.1.4/src/features/references.js:83:13
```
