### ISSUE TITLE
UML features don't seem to work despite installing PlantUML

### ISSUE THREAD

**Issue by artdgn** [Consensys/vscode-solidity-auditor#122]
I've tried following the suggestion in https://github.com/ConsenSys/vscode-solidity-auditor/issues/85 but nothing worked. I'm using ubuntu linux (installed graphviz).

PlantUML suggestions in actions menu do show up (when typing `uml` in actions menu), but `Solidity Visual Developer` suggestions for UML don't show. Other SVD suggestions do show.

**Comment by tintinweb** [comment]
Hey @artdgn,

It works for me on macos. please run `cmd + shift + p: toggle developer tools` and provide any relevant/recent errors you see in the console, and I'll investigate.

cheers.

**Comment by tintinweb** [comment]
auto-close due to inactivity. please re-open if the problem still persists.
