### ISSUE TITLE
Immutable Keyword Doesn't Have Highlighting

### ISSUE THREAD

**Issue by cyberdisc0** [ConsenSys/vscode-solidity-auditor#124]
The immutable keyword has no syntax highlighting. Is there a reason for this? Would like to see this highlighted like any other keywords.

**Comment by tintinweb** [comment]
added to 'safe keywords' (highlighted like `constant`). see https://github.com/tintinweb/vscode-solidity-language/releases/tag/v0.0.7

cheers 🙌
