### ISSUE TITLE
Bug: Named parameters incorrectly highlighted

### ISSUE THREAD

**Issue by DrakeEvans** [Consensys/vscode-solidity-auditor#132]
Solidity supports named function parameters https://docs.soliditylang.org/en/v0.8.19/control-structures.html#function-calls-with-named-parameters

however, this displays incorrect param highlighting:
![image](https://user-images.githubusercontent.com/31104161/232155269-93b1945b-ea4c-4cb0-a318-5e064ff6935a.png)

You can see that the checkpointTimestamp on the left is part of the params of the invoked function _calculateCheckpointAdd, it should not be marked with upArrow just as deltaFxs is not highlighted directly above

**Comment by tintinweb** [comment]
addressed with: https://github.com/tintinweb/solidity-workspace/pull/3
