### ISSUE TITLE
Outline not loading for some files

### ISSUE THREAD

**Issue by Minh-Trng** [Consensys/vscode-solidity-auditor#139]
For some `.sol` files I encounter the issue that the outline (giving an overview of all functions, modifiers and variables in the file) does not load:

![image](https://github.com/Consensys/vscode-solidity-auditor/assets/46103853/012cc1d8-7bfd-43cb-8625-d0e82e304e79)

This also affects the Syntax highlighting and navigation from the Visual Developer extension:

![image](https://github.com/Consensys/vscode-solidity-auditor/assets/46103853/fae1b1a9-5fec-4747-a7df-c9d9f9fc57ce)

an example of this is the following: https://github.com/code-423n4/2023-09-maia/blob/main/src/RootPort.sol

I checked the following:
- the file does compile properly, all tests run
- all imports can be navigated to by using CTRL+LeftClick
- I tried removing all comments, in case any of them are weirdly formatted

**Comment by vquelque** [comment]
Hi @Minh-Trng,
I tried reproducing the bug with the file you submitted, but I couldn't. The bug might have to do with your particular vscode configuration. 
Could you maybe check the console (help>toggle developer tools) and check if there is an error message returned by the extension?

**Comment by Minh-Trng** [comment]
hey @vquelque, thanks for taking a look! 

here is what I see in the console:

![image](https://github.com/Consensys/vscode-solidity-auditor/assets/46103853/5f12d680-7819-4f7f-a2cd-ce23430ea881)

![image](https://github.com/Consensys/vscode-solidity-auditor/assets/46103853/494cf63b-62da-4e5d-91ad-1da2f9db1fc7)

**Comment by vquelque** [comment]
Ok. Could you host a zip of your `2023-09-maia` folder and provide the link?

**Comment by Minh-Trng** [comment]
> Ok. Could you host a zip of your `2023-09-maia` folder and provide the link? @Minh-Trng

The issue occured to me on the repo of the file without any modifications: https://github.com/code-423n4/2023-09-maia/tree/main

I just managed to replicate the issue on another windows 10 machine with the following steps:

- install VsCode
- install the solidity visual developer extension
- download the zip of the repo and unzip it
- open the directory in VsCode and then try to show the outline on `RootPort.sol`

**Comment by vquelque** [comment]
Thanks for the details @Minh-Trng. This should be fixed in the next release 😀

**Comment by Minh-Trng** [comment]
> Thanks for the details @Minh-Trng. This should be fixed in the next release 😀

I am the one who has to thank 😊
Great extension that has become an essential part of my workflow
