### ISSUE TITLE
Feature request: 'Find references'

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/vscode-solidity-auditor#26]
JS language support has a really nice 'find references' feature, which would be really nice to have here. My use case would be highlighting sensitive state vars so I can review any code that touches it. 

![image](https://user-images.githubusercontent.com/23033765/61905014-0d4f4f00-aef6-11e9-8066-17a3b04f0643.png)

A similar feature would be the ability to highlight a state var, with an icon. Much like how arguments are indicated an arrow in the extension.

**Comment by tintinweb** [comment]
👍
