### ISSUE TITLE
Graphing features aren't rendering graphs

### ISSUE THREAD

**Issue by Austin-Williams** [ConsenSys/vscode-solidity-auditor#29]
Clicking on "report", "graph (this)", "graph", "inheritance", "parse", and "flatten" result in no action. No graph is rendered, no text file is created, and no errors are shown.

Clicking on "funcSigs" does work -- it produces a text file as expected.

I'm running version 0.0.17.

**Comment by tintinweb** [comment]
Hi @Austin-Williams,

any chance you can share the contract file you are trying to graph? `flatten` might require an `npm install` to be able t resolve dependencies.

**Comment by ktimam** [comment]
Facing same issue. It is giving the following error in Output - Log (Window):
[renderer1] [error] abort({"errno":-4058,"syscall":"open","code":"ENOENT","path":"........

**Comment by DeepitPK** [comment]
same error: does not display the graph and the UML appears as a text file

**Comment by tintinweb** [comment]
> same error: does not display the graph and the UML appears as a text file

@DeepitPK Please install the plantuml extension as noted in the UML text to auto-render it.

**Comment by DeepitPK** [comment]
Than

> > same error: does not display the graph and the UML appears as a text file
> 
> @DeepitPK Please install the plantuml extension as noted in the UML text to auto-render it.

Thanks!

**Comment by tintinweb** [comment]
@Austin-Williams are you still facing this issue?

**Comment by tintinweb** [comment]
Updated the graph extension to fix issues when using VSCode on Windows.
Let me know if anyone is still facing this issue otherwise I am closing it. Thanks 🙌
