### ISSUE TITLE
Wrong arrow direction for inheritance property in plantuml script generation

### ISSUE THREAD

**Issue by DeepitPK** [ConsenSys/vscode-solidity-auditor#34]
**Describe the bug**
Uml function generate a wrong uml class diagram.
For example, following Solidity contract:

```
pragma solidity ^0.5.0;

import "openzeppelin-solidity/contracts/math/SafeMath.sol";
import "./Stoppable.sol";

contract StoppableElement is Stoppable {
    using SafeMath for uint256;
    constructor () Stoppable(false) public {
    }
}
```
where StoppableElement derive from Stoppable class, generate following plantuml script and diagram:

```
@startuml
' -- for auto-render install: https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml
' -- options --



' -- classes --


class StoppableElement {
    ' -- inheritance --
	{abstract}Stoppable

    ' -- usingFor --
	{abstract}📚SafeMath for [[uint256]]

    ' -- vars --

    ' -- methods --
	+**__constructor__**()

}
' -- inheritance / usingFor --
StoppableElement <|--[#DarkGoldenRod] Stoppable
StoppableElement <|..[#DarkOliveGreen] SafeMath : //for uint256//

@enduml
```

where inheritance arrow is in wrong direction.

**Expected behavior**
Inheritance tags should be:
```
' -- inheritance / usingFor --
Stoppable <|--[#DarkGoldenRod] StoppableElement
SafeMath <|..[#DarkOliveGreen] StoppableElement : //for uint256//
```

**Screenshots**
![StoppableElement](https://user-images.githubusercontent.com/37345946/69245781-c7567f00-0ba7-11ea-9c9b-38e3f0245c45.png)
should be:
![StoppableElement](https://user-images.githubusercontent.com/37345946/69246073-4e0b5c00-0ba8-11ea-8bd4-cb6a57ec068c.png)

**Comment by tintinweb** [comment]
Good catch, thanks @DeepitPK!

I've opted to change the arrow direction and avoid that plantuml re-arranges the graph. should be merged and released with #37 soon.
