### ISSUE TITLE
Windows: Codelenses not showing up

### ISSUE THREAD

**Issue by Bobface** [ConsenSys/vscode-solidity-auditor#35]
I have just freshly installed the plugin on Windows 10 VS Code. The codelenses are not showing up for me. I have installed Surya and Graphviz before.

I saw that there is a bug mentioned about codelenses not showing up. So I changed the file and saved it to trigger a reload but it doesn't help. Also uninstalled / reloaded the plugin multiple times. The settings for codelenses are enabled.

I'm not sure what exactly I need to post so you can investigate, just let me know.

**Comment by tintinweb** [comment]
Hi @Bobface,

please provide the source code and I'll investigate.

cheers,
tin

**Comment by Bobface** [comment]
I don't get them at all, doesn't matter the code I am looking at. For example looking at [MakerDAO's dss ](https://github.com/makerdao/dss) they don't show up.

**Comment by tintinweb** [comment]
🤔 

![image](https://user-images.githubusercontent.com/2865694/71203114-b3349900-229d-11ea-8638-48690c05650c.png)

* did you get an error that the extension failed to run? (like a red error popup)
* does the developer console show any errors? can you provide a snapshot of the last loglines? (cmd+shift+p -> developer: toggle developer tools)
* please check if `mode.active` and `codelense.enable` are enabled in code -> preferences -> settings.

![image](https://user-images.githubusercontent.com/2865694/71203267-f8f16180-229d-11ea-8cd2-466bd6a5fbb3.png)

thanks @Bobface

**Comment by Bobface** [comment]
Both options are enabled and there is no error popup. There is an error in the developer console though which seems to be related to the Codelenses:

![err](https://user-images.githubusercontent.com/10945014/71207458-36a6b800-22a7-11ea-8ff4-7839685a7363.png)

**Comment by Arnas-Kucinskas** [comment]
Hello, I'm experiencing same symptoms. And problem looks to be very similar if no the same. M
aybe some additional logs will be of use.

I'm getting the same error as bobface "Cannot read property 'contracts' of undefined" when opening .sol file file. But i do get aditional errors when trying to run surya graph functionality. 
All of the errors say "no such file or directory, open" regarding the smart contract file.

[logs.log](https://github.com/ConsenSys/vscode-solidity-auditor/files/4007324/logs.log)

**Comment by tintinweb** [comment]
Thanks for the stacktrace @Bobface @Arnas-Kucinskas. will look into this asap!

**Comment by tintinweb** [comment]
vscode and path separators on windows.. what a mess 🙄
you might want to use it on macos in the meantime until I am done with cleaning up the os dependant parts :D

**Comment by tintinweb** [comment]
@Bobface, here's a preview version of the windows compatible visual auditor extension. Let me know if that fixes your problem and I am going to publish pending some cross OS tests.

[solidity-visual-auditor-0.0.21.vsix (Save Link As -> .vsix; remove the .png extension!)](https://user-images.githubusercontent.com/2865694/72028568-52d4be00-3283-11ea-93ac-792bdb01cd56.png)

**Comment by Bobface** [comment]
@tintinweb It works, thank you!
