### ISSUE TITLE
ftrace not doing anything

### ISSUE THREAD

**Issue by hacker-DOM** [ConsenSys/vscode-solidity-auditor#44]
Hi,

I am on 0.0.22. When I click `funcSig`, I correctly get the function signature. But when I click `ftrace`, nothing happens. Here is the top most output from my dev console:

```
console.ts:137 [Extension Host] stack trace: ReferenceError: opts is not defined
at Object.FunctionCall (/Users/dteiml/.vscode/extensions/tintinweb.solidity-visual-auditor-0.0.22/node_modules/surya/lib/ftrace.js:563:13)
```

**Comment by tintinweb** [comment]
thanks for also filing this upstream @hacker-DOM. Should be fixed with the next release updating surya.

cheers,
tin

**Comment by vvlnko** [comment]
hi, buddy. ftrace doesn't work for huge functions of TraderJoe. AddLiquidity, RemoveLiquidity, Swap, etc. Could u plz fix it?

**Comment by Renzo1** [comment]
I am current facing the same issue. Any help please?
