### ISSUE TITLE
Extra characters (lineNumber) in Declaration path

### ISSUE THREAD

**Issue by shayanb** [ConsenSys/vscode-solidity-auditor#5]
**Version**: 0.0.11

It seems that the LineNumber:CharacterNumber is included in the dependency path, which leads to failure to "Jump to Declaration".

e.g.:
When hover on a mapping, this message is shown:
`(mapping( bytes32=>Entry )) StateVar HashRegistrar._entries (Declaration: #16)`

When clicked on `(Declaration: #16)` VSCode tries to open a file in the "correct" path but wrong file name: `HashRegistrar.sol:133:1`

```
Unable to open 'HashRegistrar.sol:133:1': File not found (file:///PATH_TO_THE_DIRECTORY/node_modules/@ensdomains/ens/contracts/HashRegistrar.sol:133:1).
```

**Comment by shayanb** [comment]
Tried to fix this but rather learning the fix from you rather than spending hours understanding `extension.js` :)

**Comment by tintinweb** [comment]
don't try to understand it just yet. it's time to refactor that mess :)
the jump to declaration is not really working atm. need to figure out the uri for jump to file:line:col with vscode first
