### ISSUE TITLE
Does not work with newer versions of solidity

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/vscode-solidity-auditor#50]
I'm seeing this in the VSCode console: ![image](https://user-images.githubusercontent.com/23033765/82945084-5636c080-9f6a-11ea-96aa-2970cdae4e66.png)

I hope it will be fixed by this: https://github.com/ConsenSys/surya/pull/142, and updating this repo to use the community parser.

**Comment by tintinweb** [comment]
fixed with #53
