### ISSUE TITLE
Alphabetical order in the top-level contracts sidebar section

### ISSUE THREAD

**Issue by GNSPS** [ConsenSys/vscode-solidity-auditor#54]
Can we have the "Top-level contracts" sidebar section display the results in alphabetical order? 😊

**Comment by tintinweb** [comment]
@GNSPS alphabetical order for filenames or the full path? 

full-path somewhat preserves the folder structure
filename does not preserve the folder structure.

```
/a/b/c/d/xyz.sol
/a/b/c/d/b.sol   
/a/b/c/d/a.sol    //first item
/a/x/c/d/aa.sol  // would be 2nd in filename sort, last in full-path sort
```

**Comment by GNSPS** [comment]
I actually meant the file names because there is no way I can search for the files in that section unless they are in some kind of order. And when there are a lot of files it's harder to look for each one.
