### ISSUE TITLE
Constructor visibility warning issue

### ISSUE THREAD

**Issue by MXmaster2s** [ConsenSys/vscode-solidity-auditor#61]
When a constructor visibility is set to public, a warning is shown" `Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient`
However, explicitly mentioning is needed; else there is an error when trying to compile: `SyntaxError: No visibility specified. Did you intend to add "public"?`

I'm using Truffle v5.1.40 (core: 5.1.40) and Node v14.8.0

**Comment by tintinweb** [comment]
Hi @MXmaster2s,

this appears to be a solidity compiler warning/error message (see [solidity](https://github.com/ethereum/solidity/blob/2fece0724ab1284a97d7b7a078253e388e5bb9d3/test/libsolidity/syntaxTests/constructor/constructible_internal_constructor.sol) which is not emitted by this extension. 

Please refer to the solidity compiler for more information but this may be a good indicator that the compiler has problems with your source code.

cheers 🙌
