### ISSUE TITLE
What does the complexity mean? Is it the gas to be costed?

### ISSUE THREAD

**Issue by zhengger** [ConsenSys/vscode-solidity-auditor#62]
Outline View:
    populates VS Code outline view with sourceUnit and contract layout
    contracts, stateVars, methods, inherited names
    annotates security relevant information (visibility, ...)
    calculates complexity rating
    annotations functions with information about whether they are accessing stateVars

**Comment by tintinweb** [comment]
Hey @zhengger,

the complexity rating is based on the AST and **not** gas costs. It is more a naive indicator for code complexity (source code; not evm bytecode). For example, loops, branches, transfer of funds makes code more complex from a reviewers perspective.

hope that helps.
cheers,
tin

**Comment by zhengger** [comment]
Hi @tintinweb, thank you!

Could you give me a little more illustration on what's the purpose of "complexity rating", i.e. what can I use it for?

Thank you so much!

**Comment by tintinweb** [comment]
@zhengger probably most interesting to auditors who want to quickly find functions with a high code complexity. Note that you can disable this via config setting `solidity-va.outline.extras`.
