### ISSUE TITLE
funcSig to use recursive type resolving (AST) rather than lexical parsing

### ISSUE THREAD

**Issue by shayanb** [Consensys/vscode-solidity-auditor#69]
I used the funcSigs and found out there’s a discrepancy between what it shows and what it should be:

`function _executeActionsFromFL(Task memory _currTask, bytes32 _flAmount) `

Which SVA shows as :
`4517bb07  =>  _executeActionsFromFL(Task,bytes32)`

But the actual func signature that calls this function as the callback is: `0xd6741b9e`

Apparently, the struct that is in the function argument (abi) should be expanded.
```
    struct Task {
        string name;
        bytes[][] callData;
        bytes[][] subData;
        bytes32[] actionIds;
        uint8[][] paramMapping;
    }
```
Something like: "_executeActionsFromFL((address,address,uint256,...),bytes32)"

**Comment by tintinweb** [comment]
related to #77
