### ISSUE TITLE
Feature Request: UnitTest stub support for Hardhat/Ethers (instead of truffle)

### ISSUE THREAD

**Issue by NoahMarconi** [ConsenSys/vscode-solidity-auditor#70]
If adding something like this wouldn't clutter things too much I'd be happy to work on a pull request.

**Comment by tintinweb** [comment]
We can make this configurable if it is useful. Can you suggest a template @NoahMarconi ?

**Comment by defistar** [comment]
@tintinweb 
Thanks for offering to make this configurable.
We are working on testTemplate for hardhat. 
We will share the Pull-Request by next-week.

**Comment by tintinweb** [comment]
thx for the PR. added a configurative option to select the default unittest template. 
![image](https://user-images.githubusercontent.com/2865694/122207344-5326af00-cea2-11eb-912f-f813847aeb23.png)
