### ISSUE TITLE
Preview not showing graphs

### ISSUE THREAD

**Issue by flipNFTs** [ConsenSys/vscode-solidity-auditor#71]
I can get the diagraph G with meaningful contents in it, however, the Preview tab does not have the desired graph showing up. Actually it is not showing up anything. I have reopenit the editor after installation. Wondering why this is case. Thanks.

**Comment by flipNFTs** [comment]
![image](https://user-images.githubusercontent.com/83438620/117389606-300df480-af1f-11eb-9536-c426d7653fc0.png)
![image](https://user-images.githubusercontent.com/83438620/117389615-3308e500-af1f-11eb-982f-b18012b8e2b1.png)

**Comment by flipNFTs** [comment]
As you can see, nothing is shown on Preview tab, and digraph G tab seems fine.

**Comment by flipNFTs** [comment]
One possible reason is I don't have Java installed on my machine. Is java required?

**Comment by tintinweb** [comment]
hey @flipNFTs,

would be great if you could check if you're seeing any errors in the developer tools console: cmd -> toggle developer tools -> console

**Comment by gnmaxim** [comment]
> One possible reason is I don't have Java installed on my machine. Is java required?

did you fix this?
