### ISSUE TITLE
Empty Call Graph

### ISSUE THREAD

**Issue by DakshMiglani** [ConsenSys/vscode-solidity-auditor#72]
- Call Graph is empty, screenshot:
![image](https://user-images.githubusercontent.com/23355449/117540065-fb875f00-b02a-11eb-9f8c-43fd4ccd7f27.png)

- Clicking the contract interaction graph button does nothing

**Comment by gnmaxim** [comment]
Same thing started to happen to me on a fresh installation of Fedora 34, no image on "inheritance" but generates metadata.

**Comment by tintinweb** [comment]
do you have graphviz installed on your system? @gnmaxim @DakshMiglani

**Comment by tintinweb** [comment]
1. is graphviz installed and globally available on your system? required by https://www.npmjs.com/package/graphviz (this is what's rendering the graphs)
2. what's your OS + vscode version?
3. are there any errors in the developer tools console: cmd -> toggle developer tools -> console
4. link to codebase / solidity file + what feature of the extension are you referring to? (call trace from codelense (this graph/graph), right click call trace, cockpit view call trace)
5. did it suddenly fail and used to work before or is this the first time you're using this feature and it's not working.

**Comment by DakshMiglani** [comment]
1. yes
2. OSX 11.2.3 (M1) + VSC 1.56.2
3. no
4. any solidity file, tried with many opensource repos
5. first time

**Comment by tintinweb** [comment]
looks like this is broken since 1.56.0. vscode introduced some changes to the webview API and it seems like the renderer does not receive messages anymore. I've filed this with https://github.com/microsoft/vscode/issues/123822 and will continue to investigate.

**Comment by gnmaxim** [comment]
> 1. is graphviz installed and globally available on your system? required by https://www.npmjs.com/package/graphviz (this is what's rendering the graphs)
> 2. what's your OS + vscode version?
> 3. are there any errors in the developer tools console: cmd -> toggle developer tools -> console
> 4. link to codebase / solidity file + what feature of the extension are you referring to? (call trace from codelense (this graph/graph), right click call trace, cockpit view call trace)
> 5. did it suddenly fail and used to work before or is this the first time you're using this feature and it's not working.

1. yes, graphviz-2.44.0-17.fc34.x86_64
2. Fedora 34, VSCode 1.56.2
3. `Unexpected command: setConfig`
    `Unexpected command: renderDot`
    `Invalid asm.js function definition doesn't match use (viz.js:33)`
4. any solidity file
5. it worked on Fedora 33 and an older version of VSCode

**Comment by tintinweb** [comment]
thanks, should be fixed by updating the vscode-interactive-graphview extension to v0.0.11 (addressing https://github.com/tintinweb/vscode-interactive-graphviz/issues/15). this extension is creating the graph preview for the solidity extension.

let me know if the problem still persists @DakshMiglani @gnmaxim

cheers

**Comment by DakshMiglani** [comment]
Blimey! Thank you @tintinweb 😛
