### ISSUE TITLE
Disable stateVar highlighting

### ISSUE THREAD

**Issue by grenos** [ConsenSys/vscode-solidity-auditor#73]
I'm trying to disable stateVar highlighting but it doesn't seem to work. Did it both globally from the settings and for the current workspace. Also checked the json file and it seems to have both "deco" values set to false. On the other hand I had no problems disabling hilighting  function arguments.

`  "solidity-va.deco.arguments": false,
  "solidity-va.deco.statevars": false`

<img width="744" alt="Screenshot 2021-05-26 at 13 46 34" src="https://user-images.githubusercontent.com/26184688/119654726-09a9ed80-be29-11eb-9c8d-f83f6b30a21d.png">

Not sure if there's something wrong on my end. Maybe a problem with another extension?

**Comment by tintinweb** [comment]
Thanks for the report. Definitely a bug. Should be fixed with v0.0.32 (published today).

cheers
