### ISSUE TITLE
Add "Surya - graph (this)" to the command palette

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/vscode-solidity-auditor#76]
**Context**

For my current workflow, I usually find the `Surya - graph(this)` functionality more useful as it is less noisy and helps me to better understand a subset of a large codebase. 

However this is only accessible via code lens which I keep disabled most of the time, since it adds clutter. 

**Request**

I would like to have access to the `graph(this)` function from the command palette.

**Comment by tintinweb** [comment]
* fully customizable codelenses
