### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by aemmosa** [ConsenSys/vscode-solidity-auditor#79]
- Issue Type: `Bug`
- Extension Name: `solidity-visual-auditor`
- Extension Version: `0.1.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by tintinweb** [comment]
Can you provide more information?

**Comment by tintinweb** [comment]
closed 🤷
