### ISSUE TITLE
Is a "zoom in" ability on for surya graphs possible?

### ISSUE THREAD

**Issue by Annabelle75** [ConsenSys/vscode-solidity-auditor#80]
Brilliant how it links and highlights graphs within VS Code, but for a complex contract it makes a huge graph that's too small to view, even on 4K monitors. 

I couldn't figure out a way to zoom just the graph/the graph's tab, is that possible? If not, can it be made possible?

Thanks for such an awesome plugin, really appreciate your work :-)

**Comment by tintinweb** [comment]
Hi @Annabelle75 🙌 

mousewheel up/down should zoom in/out.

thanks & cheers ,
tin

**Comment by Annabelle75** [comment]
Well, duh, that's too obvious so I never would've thought of that. :-(

In my defense, I'm (still) on an IBM -- not Lenovo -- pointing stick keyboard. Talk about "built to last"!

Thank you so much for responding!

**Comment by tintinweb** [comment]
easy :) I never figured out how to navigate that pointing stick thingie on my old lenovo 😂 glad you do. cheers
