### ISSUE TITLE
Display compilation errors in my Solidity code

### ISSUE THREAD

**Issue by lcswillems** [ConsenSys/vscode-solidity-auditor#81]
Hi!

Something I like about [this VSCode Solidity extension](https://github.com/juanfranblanco/vscode-solidity) is that it shows me compilation errors directly in my Solidity code.

I don't think it is possible in your VSCode extension. It would be nice to have such a feature.

**Comment by tintinweb** [comment]
Hi @lcswillems 🙌 

would be nice but the extension is only parsing your code without actually compiling it. nice side-effect: it's way faster than extensions that actually compile code + we can allow for an error of margin without having to bug you while typing.

cheers,
tin

**Comment by lcswillems** [comment]
"nice side-effect: it's way faster than extensions that actually compile code + we can allow for an error of margin without having to bug you while typing." : I don't think it is a nice side-effect, I think it is more a big limitation from my point of view. It is not way faster than VSCode Solidity extension for example.

Why this extension is only "only parsing your code without actually compiling it"? Why this limitation? You caracterize your extension as "An extension that supports developers in writing secure and well understood code". Displaying errors as soon as they are written seems to go in this direction.

**Comment by tintinweb** [comment]
since this extension is not compiling your code it, unfortunately, cannot provide you with compiler output. however, as noted, the two extensions are compatible which should allow you to get the best of both worlds 🙌 

cheers,
tin

**Comment by lcswillems** [comment]
Okay, thank you for the explanations! I am going to use both!
