### ISSUE TITLE
how to debug bytecode

### ISSUE THREAD

**Issue by eladalkabets2603** [ConsenSys/vscode-solidity-auditor#88]
i have recenlty downloaded the extension to vscode, and used it to get bytecode of contracts.
i was compiling 2 different contracts and got the same bytecode for both of then (excluding the metadata).
can you point me to the line in the codewhere you augment the bytecode while hoverig over contract address?, and the actuall place the function is called (new to js so might have missed it)?
thanks

**Comment by tintinweb** [comment]
hey @eladalkabets2603,

should be around this function: https://github.com/ConsenSys/vscode-ethover/blob/master/src/features/evm.js#L251

note that the actual code resides with the `vscode-ethover` extension which is bundled to this one.

cheers
