### ISSUE TITLE
[request] add more audit annotations/bookmarks

### ISSUE THREAD

**Issue by StErMi** [ConsenSys/vscode-solidity-auditor#89]
Would be possible to configure or add more audit annotations/bookmarks?

I would like to be able to specify things like `@audit-wontfix` or `@audit-fixed` or whatever else so the plugin should allow me to specify new `@audit-MYNAME` and change the color of that bookmark.

**Comment by tintinweb** [comment]
Hey @StErMi, 

you can customize the extension in the settings. see FAQ: https://marketplace.visualstudio.com/items?itemName=tintinweb.vscode-inline-bookmarks

something like this would do:

![image](https://user-images.githubusercontent.com/2865694/152762548-022b7f78-19f3-4012-81b4-ff76c7ef4227.png)
