### ISSUE TITLE
Enhancement: Global project funcSig grep

### ISSUE THREAD

**Issue by spaceh3ad** [ConsenSys/vscode-solidity-auditor#94]
Hi, would it be possible to grep globally a particular funcSig? It would help a lot at debugging and Reverse Engineering.

**Comment by tintinweb** [comment]
So, you basically need a list of all funcSigs in the workspace?

**Comment by tintinweb** [comment]
would this solve your problem? https://www.npmjs.com/package/hardhat-function-signatures
